"""Add full_name column to Appointment model

Revision ID: 0019ef647595
Revises: 63b829f1f26b
Create Date: 2023-09-08 17:09:50.895997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019ef647595'
down_revision = '63b829f1f26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
