"""Recreate the database

Revision ID: cc9686283684
Revises: 7aab9d2bc227
Create Date: 2023-09-08 17:56:48.108919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9686283684'
down_revision = '7aab9d2bc227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_slot', schema=None) as batch_op:
        batch_op.alter_column('booking_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_slot', schema=None) as batch_op:
        batch_op.alter_column('booking_time',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
