"""Your migration message

Revision ID: d29568bc8ced
Revises: cc9686283684
Create Date: 2023-09-10 20:50:11.240465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29568bc8ced'
down_revision = 'cc9686283684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booked_slot', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
